data_dir: "datasets"
model_path: "models/model.pth"
batch_size: 32
lr: 0.001
epochs: 10

defaults:
    - _self_
    - override hydra/hydra_logging: disabled
    - override hydra/job_logging: disabled
hydra:
    output_subdir: null
    run:
        dir: .
